### ISSUE TITLE
Bug: Multiple imagemaps on different instruments fail

### ISSUE THREAD

**Issue by steentje34** [denshade/redcap_customimagemap#1]
It seems that, if the project contains multiple imagemaps on different instruments, only the first imagemap will render. All subsequent imagemaps on other instruments fail to render and throw an error in the console "Uncaught Found no map elements with id xyz".
Could this be fixed?

**Comment by denshade** [comment]
The hooks are injected on all instruments. I've added a try catch to show the problems as warnings rather than errors. This will show warnings without stopping the flow of execution of other imagemaps.
