### ISSUE TITLE
"found no elements with id {}"

### ISSUE THREAD

**Issue by devincowan** [denshade/redcap_customimagemap#3]
@denshade I tried to make a simple example instrument using your RC EM. Looks like a great tool, but I have an issue:

When I open the instrument to test my imagemap, image is shown but nothing is clickable. Also, it shows broken html below the image.

Within browser, my console shows:

> Found no map elements with id image-map

Here are the fields that I created....

Field label in descriptive text field:
```
<img id="beam_img" src="https://devincowan.host/l/public/uploads/small/df0da29ac68249405fd92e0bcadb2ba1.jpg" usemap="#image-map">

<map id="image-map" name="image-map">
    <area target="" alt="sun" title="sun" coords="468,122,218,2" shape="rect">
    <area target="" alt="tree" title="tree" coords="78,282,182" shape="circle">
    <area target="" alt="tree2" title="tree2" coords="549,346,530,297,512,258,530,229,551,215,519,191,495,190,483,186,488,173,499,161,518,143,483,124,432,140,428,195,431,260,419,297,418,335,418,349" shape="poly">
</map>
```
Action tag:
`@CUSTOM_IMAGEMAP=registerImageMap("beam_img", "image-map", "checkboxes", "rgba(255, 0, 0, 0.2)", "alt");`

Checkboxes field screenshot:
![image](https://user-images.githubusercontent.com/17934193/77005494-7de42980-6926-11ea-9a2d-91bfc735a137.png)

Descriptive text screenshot:
![image](https://user-images.githubusercontent.com/17934193/77005544-99e7cb00-6926-11ea-8924-2aa72ba30f49.png)

Screenshot of the Online Designer:
![image](https://user-images.githubusercontent.com/17934193/77005618-b71c9980-6926-11ea-991c-7e6ac9351365.png)
(note the "< map" tag...

**Comment by denshade** [comment]
I'm afraid this is a problem in REDCap. In older versions of REDCap all map and area elements are transformed into <&nbsp;map> as a security measure.
I've tried it on REDCap v. 9.5.18 and it's working perfectly. 
More on that here:
https://community.projectredcap.org/questions/49526/imagemaps-in-descriptive-text-corrupted.html

So basically you should upgrade REDCap or adjust Classes/System.php to include map and area.

**Comment by devincowan** [comment]
got it thanks!
