### ISSUE TITLE
How do I pass multiple selections into the Results field?

### ISSUE THREAD

**Issue by dhinostroza** [denshade/redcap_customimagemap#6]
Hi, Simon,
In the screenshot below, I have selected areas 17 (front) and 50 (back), of 74 possible options, yet in the results field, only area 17 is captured.

The documentation states that each calculation should be in its own line, like this:
if([body_male_areas(1)] = 1, 1, 0)
if([body_male_areas(2)] = 1, 2, 0)
if([body_male_areas(3)] = 1, 3, 0)
if([body_male_areas(4)] = 1, 4, 0)
if([body_male_areas(5)] = 1, 5, 0)
if([body_male_areas(6)] = 1, 6, 0)... and so on to 74
But this throws an error, so I added an OR to each line, like this:

if([body_male_areas(1)] = 1, 1, 0) OR if([body_male_areas(2)] = 1, 2, 0) OR if([body_male_areas(3)] = 1, 3, 0) OR if([body_male_areas(4)] = 1, 4, 0) OR if([body_male_areas(5)] = 1, 5, 0) OR if([body_male_areas(6)] = 1, 6, 0)... and so on to 74

The documentation also states that an additional calculated field is needed to aggregate the results. How should the calculation be written to allow viewing of multiple selections?

![Screenshot 2024-06-05 at 9 59 55 AM](https://github.com/redcapuzgent/redcap_customimagemap/assets/18691188/ed69d078-d1c7-4591-82c6-0a97d5257035)

**Comment by steentje34** [comment]
@dhinostroza To help you with your question, I need some additional information.

> The documentation states that each calculation should be in its own line, like this: if([body_male_areas(1)] = 1, 1, 0) 
> The documentation also states that an additional calculated field is needed to aggregate the results. How should the calculation be written to allow viewing of multiple selections?

- I can't seem to find this information in the External Module's documentation. Could you maybe share a link and/or screenshot to the documentation you are referring to?
- For the specific use case, can you elaborate on what you expect the result of the calculation to be?

**Comment by dhinostroza** [comment]
Dear Simon,
Sorry for causing confusion. I found a tutorial on calculated fields at https://www.ctsi.ufl.edu/files/2017/06/Calculated-Fields-%E2%80%93-REDCap-How.pdf.
I am including a screenshot.
![Screenshot 2024-06-10 at 9 29 43 AM](https://github.com/redcapuzgent/redcap_customimagemap/assets/18691188/baeb34fb-bf4b-409d-b953-5871b7e5b23e)

For the Choir Body Male, if the user selects areas 17 and 50, the result field should display:
f17, b50 or directly Abdomen (front-right), Middle Back (back-right).
All the very best,
Daniel

**Comment by steentje34** [comment]
@dhinostroza Okay, now I understand, this is not a question related to the External Module, but a REDCap related question. I will try to help you nevertheless 😃

First of all, if you want the result to display text, you will need to use a text field with @CALCTEXT (instead of a calculated field).

Next, I had hoped that changing the coding of your checkbox field and using `@CALCTEXT([body_male_areas:checked:value])` or `@CALCTEXT([body_male_areas:checked])` would do the trick, but apparently this does not function (yet) in the current REDCap version (we are on v14.0.21).
Instead, you can construct something like this:
```
concat_ws(
    ', ',
    if([body_male_areas(1)]='1', 'f1', ''),
    if([body_male_areas(2)]='1', 'f2', ''),
    if([body_male_areas(3)]='1', 'f3', ''),
    ...
)
```

I hope this guides you in the right direction!

**Comment by dhinostroza** [comment]
Thank you, Simon,
I thought creating the multi-select list of results was part of the Custom_Image module.
Anyway, I tested your @CALCTEXT([body_male_areas:checked:value]) suggestion and it works. The imagemap and the checkbox options are displayed correctly. 

For the multi-select list of results, I've tested the following variations: 
**1. A Calculation field.** If I use concat, it displays the correct numbers when a checkbox is selected. 
```
concat(
    if([body_male_areas(1)] = 1, 1, ""), 
    if([body_male_areas(2)] = 1, 2, ""), 
    if([body_male_areas(3)] = 1, 3, ""),
...
) 
```
(Screenshot attached):
![Screenshot 2024-06-11 at 12 12 15 PM](https://github.com/redcapuzgent/redcap_customimagemap/assets/18691188/7d6dac50-ffa6-4b07-be89-9a407420b752)
Despite many tries and combinations, I cannot add separators without damaging the calculation

**2. A text field with the concat_ws (in the Action Tag).** The code passes the validation but doesn't work:
concat_ws(", ", if([body_male_areas(1)] = 1, "a01", ""), if([body_male_areas(2)] = 1, "a02", ""), if([body_male_areas(3)] = 1, "a03", "")
...
)
**3. A Calculation field with the concat_ws (in the Calculation Equation).** The code passes the validation but doesn't work:
concat_ws(", ", if([body_male_areas(1)] = 1, "a01", ""), if([body_male_areas(2)] = 1, "a02", ""), if([body_male_areas(3)] = 1, "a03", "")
...
)

Maybe I'm doing something that the customimagemap isn't expecting? Perhaps you can provide an XML instrument of a working customimagemap + male_body_map?

**Comment by steentje34** [comment]
Dear @dhinostroza,

As far as the External Module is concerned, everything is working as expected. The screenshot proves that you are able to click on the image and that the corresponding checkboxes are toggled.

The issue of not being able to get the output you expect is entirely REDCap-related and is not at all related to the use of the External Module. I will continue trying to help you, but please keep in mind that this is not at all EM-related.

How did you get `@CALCTEXT([body_male_areas:checked:value])` to work? I have tested this on REDCap version 14.0.21 & 14.3.13, but it did not work for me. What REDCap version are you on?

If `@CALCTEXT([body_male_areas:checked:value])` is working for you, you don't need another solution. However, if it is not working, you will need a text field with following action tag:
```
@CALCTEXT(
    concat_ws(
        ', ',
        if([body_male_areas(1)]='1', 'f1', ''),
        if([body_male_areas(2)]='1', 'f2', ''),
        if([body_male_areas(3)]='1', 'f3', ''),
        ...
    )
)
```
I have attached a functional [test project](https://github.com/user-attachments/files/15799840/testproject.zip).

**Comment by dhinostroza** [comment]
Dear @steentje34,
Custom Imagemap v1.17 works beautifully on REDCap v14.3.13 using the code you provided. A million thanks!
I understand now that coding the values and label fields are not within the scope of this EM, but I'm very grateful nonetheless for your extra help. Hopefully this issue will be of use to other perplexed users in the future.
Regarding the @CALCTEXT([body_male_areas:checked:value]), no idea. I just copied and pasted, and it worked at the first try.
All the very best,
Daniel

**Comment by dhinostroza** [comment]
Here is a screenshot of the @CALCTEXT([body_male_areas:checked:value]) field.
![Screenshot 2024-06-12 at 8 57 30 AM](https://github.com/redcapuzgent/redcap_customimagemap/assets/18691188/9ebba820-11ac-4dd7-a834-0543c4e7aeb6)
